---
language: python
python:
  - "2.7"
  - "3.7"
env:
  - TEST_PLAYBOOK=test.yml
  - TEST_PLAYBOOK=test-complete.yml

# Install ansible
addons:
  apt:
    packages:
    - python-pip

install:
  # Install ansible
  - pip install ansible

  # Check ansible version
  - ansible --version

script:
  # Basic role syntax check
  - ansible-playbook "tests/${TEST_PLAYBOOK}" -i tests/inventory --syntax-check
  # Use the role
  - ansible-playbook "tests/${TEST_PLAYBOOK}" -i tests/inventory

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
