---
- name: Initialise bare repos # noqa 303
  command: git init --bare "{{ git_repo }}.git"
  args:
    chdir: /opt/git
    creates: "/opt/git/{{ git_repo }}.git"

- name: Give bare repos dir to git user
  file:
    path: "/opt/git/{{ git_repo }}.git"
    owner: git
    group: git
    recurse: yes

- name: Install post-receive hook for automatic deployments
  template:
    src: post-receive.j2
    dest: "/opt/git/{{ git_repo }}.git/hooks/post-receive"
    owner: git
    group: git
    mode: 0700
