---
- name: Enable unprivileged user namespaces
  sysctl:
    name: kernel.unprivileged_userns_clone
    value: '1'
    state: present
    reload: yes
  when: ansible_distribution == 'Debian'

- name: Enable Overlay2 kernel module
  modprobe:
    name: overlay
    params: "permit_mounts_in_userns=1"
  when: ansible_distribution == 'Debian' and ansible_distribution_major_version >= '10'

- name: Install system dependencies for rootless docker
  apt:
    name:
      - uidmap
      - libpam-systemd
    state: present
    update_cache: yes
    cache_valid_time: 86400

- name: Install docker as user
  include_tasks:
    file: rootless-docker-as-user.yml

- name: Install systemd service for rootless docker
  template:
    src: rootless-docker.service.j2
    dest: /etc/systemd/system/rootless-docker.service

- name: Start & enable docker daemon
  systemd:
    name: rootless-docker.service
    state: started
    enabled: yes
